#pragma once

#include "cpu.h"
#include "addressing_modes.h"

// A negative cycles count is used to determine if it needs to check for page crossing and increase by one
// (absolute value is used for computing cycles)

struct addressing_data addressing[(0xFF) + 1] = {
    {&BRK, "BRK", IMPLICIT, 1, 7}, {&ORA, "ORA", INDIRECTX, 2, 6}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&SLO, "SLO", INDIRECTX, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&ORA, "ORA", ZEROPAGE, 2, 5}, {&ASL, "ASL", ZEROPAGE, 2, 5}, {&SLO, "SLO", ZEROPAGE, 2, 5}, {&PHP, "PHP", IMPLICIT, 1, 3}, {&ORA, "ORA", IMMEDIATE, 2, 2},
    {&ASL, "ASL", ACCUMULATOR, 1, 2}, {&ANC, "ANC", IMMEDIATE, 2, 2}, {&NOP, "NOP", INDIRECT, 3, 1}, {&ORA, "ORA", ABSOLUTE, 3, 4}, {&ASL, "ASL", ABSOLUTE, 3, 6}, {&SLO, "SLO", ABSOLUTE, 3, 6}, {&BPL, "BPL", RELATIVE, 2, 2}, {&ORA, "ORA", INDIRECTY, 2, -5}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&SLO, "SLO", INDIRECTY, 2, 8},
    {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&ORA, "ORA", ZEROPAGEX, 2, 4}, {&ASL, "ASL", ZEROPAGEX, 2, 6}, {&SLO, "SLO", ZEROPAGEX, 2, 6}, {&CLC, "CLC", IMPLICIT, 1, 2}, {&ORA, "ORA", ABSOLUTEY, 3, -4}, {&NOP, "NOP", IMPLICIT, 1, 1}, {&SLO, "SLO", ABSOLUTEY, 3, 7}, {&NOP, "NOP", INDIRECT, 3, 1}, {&ORA, "ORA", ABSOLUTEX, 3, -4},
    {&ASL, "ASL", ABSOLUTEX, 3, 7}, {&SLO, "SLO", ABSOLUTEX, 3, 7}, {&JSR, "JSR", ABSOLUTE, 3, 6}, {&AND, "AND", INDIRECTX, 2, 6}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&RLA, "RLA", INDIRECTX, 2, 8}, {&BIT, "BIT", ZEROPAGE, 2, 3}, {&AND, "AND", ZEROPAGE, 2, 3}, {&ROL, "ROL", ZEROPAGE, 2, 5}, {&RLA, "RLA", ZEROPAGE, 2, 5},
    {&PLP, "PLP", IMPLICIT, 1, 4}, {&AND, "AND", IMMEDIATE, 2, 2}, {&ROL, "ROL", ACCUMULATOR, 1, 2}, {&ANC, "ANC", IMMEDIATE, 2, 2}, {&BIT, "BIT", ABSOLUTE, 3, 4}, {&AND, "AND", ABSOLUTE, 3, 4}, {&ROL, "ROL", ABSOLUTE, 3, 6}, {&RLA, "RLA", ABSOLUTE, 3, 6}, {&BMI, "BMI", RELATIVE, 2, 2}, {&AND, "AND", INDIRECTY, 2, -5},
    // 50
    {&KIL, "KIL", IMPLICIT, 1, 1}, {&RLA, "RLA", INDIRECTY, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&AND, "AND", ZEROPAGEX, 2, 4}, {&ROL, "ROL", ZEROPAGEX, 2, 6}, {&RLA, "RLA", ZEROPAGEX, 2, 6}, {&SEC, "SEC", IMPLICIT, 1, 2}, {&AND, "AND", ABSOLUTEY, 3, -4}, {&NOP, "NOP", IMPLICIT, 1, 1}, {&RLA, "RLA", ABSOLUTEY, 3, 7},
    {&NOP, "NOP", INDIRECT, 3, 1}, {&AND, "AND", ABSOLUTEX, 3, -4}, {&ROL, "ROL", ABSOLUTEX, 3, 7}, {&RLA, "RLA", ABSOLUTEX, 3, 7}, {&RTI, "RTI", IMPLICIT, 1, 6}, {&EOR, "EOR", INDIRECTX, 2, 6}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&SRE, "SRE", INDIRECTX, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&EOR, "EOR", ZEROPAGE, 2, 3},
    {&LSR, "LSR", ZEROPAGE, 2, 5}, {&SRE, "SRE", ZEROPAGE, 2, 5}, {&PHA, "PHA", IMPLICIT, 1, 3}, {&EOR, "EOR", IMMEDIATE, 2, 2}, {&LSR, "LSR", ACCUMULATOR, 1, 2}, {&ASR, "ASR", IMMEDIATE, 2, 2}, {&JMP, "JMP", ABSOLUTE, 3, 3}, {&EOR, "EOR", ABSOLUTE, 3, 4}, {&LSR, "LSR", ABSOLUTE, 3, 6}, {&SRE, "SRE", ABSOLUTE, 3, 6},
    {&BVC, "BVC", RELATIVE, 2, 2}, {&EOR, "EOR", INDIRECTY, 2, -5}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&SRE, "SRE", INDIRECTY, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&EOR, "EOR", ZEROPAGEX, 2, 4}, {&LSR, "LSR", ZEROPAGEX, 2, 6}, {&SRE, "SRE", ZEROPAGEX, 2, 6}, {CLI, IMPLICIT, 1, 2}, {&EOR, "EOR", ABSOLUTEY, 3, -4},
    {&NOP, "NOP", IMPLICIT, 1, 1}, {&SRE, "SRE", ABSOLUTEY, 3, 7}, {&NOP, "NOP", INDIRECT, 3, 1}, {&EOR, "EOR", ABSOLUTEX, 3, -4}, {&LSR, "LSR", ABSOLUTEX, 3, 7}, {&SRE, "SRE", ABSOLUTEX, 3, 7}, {&RTS, "RTS", IMPLICIT, 1, 6}, {&ADC, "ADC", INDIRECTX, 2, 6}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&RRA, "RRA", INDIRECTX, 2, 8},
    // 100
    {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&ADC, "ADC", ZEROPAGE, 2, 3}, {&ROR, "ROR", ZEROPAGE, 2, 5}, {&RRA, "RRA", ZEROPAGE, 2, 5}, {&PLA, "PLA", IMPLICIT, 1, 4}, {&ADC, "ADC", IMMEDIATE, 2, 2}, {&ROR, "ROR", ACCUMULATOR, 1, 2}, {&ARR, "ARR", IMMEDIATE, 2, 2}, {&JMP, "JMP", INDIRECT, 3, 5}, {&ADC, "ADC", ABSOLUTE, 3, 4},
    {&ROR, "ROR", ABSOLUTE, 3, 6}, {&RRA, "RRA", ABSOLUTE, 3, 6}, {&BVS, "BVS", RELATIVE, 2, 2}, {&ADC, "ADC", INDIRECTY, 2, -5}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&RRA, "RRA", INDIRECTY, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&ADC, "ADC", ZEROPAGEX, 2, 4}, {&ROR, "ROR", ZEROPAGEX, 2, 6}, {&RRA, "RRA", ZEROPAGEX, 2, 6},
    {&SEI, "SEI", IMPLICIT, 1, 2}, {&ADC, "ADC", ABSOLUTEY, 3, -4}, {&NOP, "NOP", IMPLICIT, 1, 1}, {&RRA, "RRA", ABSOLUTEY, 3, 7}, {&NOP, "NOP", INDIRECT, 3, 1}, {&ADC, "ADC", ABSOLUTEX, 3, -4}, {&ROR, "ROR", ABSOLUTEX, 3, 7}, {&RRA, "RRA", ABSOLUTEX, 3, 7}, {&NOP, "NOP", ZEROPAGEX, 2, 1}, {&STA, "STA", INDIRECTX, 2, 6},
    {&NOP, "NOP", IMMEDIATE, 2, 2}, {&AXS, "AXS", INDIRECTX, 2, 6}, {&STY, "STY", ZEROPAGE, 2, 3}, {&STA, "STA", ZEROPAGE, 2, 3}, {&STX, "STX", ZEROPAGE, 2, 3}, {&AXS, "AXS", ZEROPAGE, 2, 3}, {&DEY, "DEY", IMPLICIT, 1, 2}, {&NOP, "NOP", IMMEDIATE, 2, 2}, {&TXA, "TXA", IMPLICIT, 1, 2}, {&XAA, "XAA", IMMEDIATE, 2, 2},
    {&STY, "STY", ABSOLUTE, 3, 4}, {&STA, "STA", ABSOLUTE, 3, 4}, {&STX, "STX", ABSOLUTE, 3, 4}, {&AXS, "AXS", ABSOLUTE, 3, 4}, {&BCC, "BCC", RELATIVE, 2, 2}, {&STA, "STA", INDIRECTY, 2, 6}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&AXA, "AXA", INDIRECTY, 2, 6}, {&STY, "STY", ZEROPAGEX, 2, 4}, {&STA, "STA", ZEROPAGEX, 2, 4},
    // 150
    {&STX, "STX", ZEROPAGEY, 2, 4}, {&AXS, "AXS", ZEROPAGEY, 2, 4}, {&TYA, "TYA", IMPLICIT, 1, 2}, {&STA, "STA", ABSOLUTEY, 3, 5}, {&TXS, "TXS", IMPLICIT, 1, 2}, {&TAS, "TAS", ABSOLUTEY, 3, 5}, {&SHY, "SHY", ABSOLUTEX, 3, 5}, {&STA, "STA", ABSOLUTEX, 3, 5}, {&SHX, "SHX", ABSOLUTEY, 3, 5}, {&AXA, "AXA", ABSOLUTEY, 3, 5},
    {&LDY, "LDY", IMMEDIATE, 2, 2}, {&LDA, "LDA", INDIRECTX, 2, 6}, {&LDX, "LDX", IMMEDIATE, 2, 2}, {&LAX, "LAX", INDIRECTX, 2, 6}, {&LDY, "LDY", ZEROPAGE, 2, 3}, {&LDA, "LDA", ZEROPAGE, 2, 3}, {&LDX, "LDX", ZEROPAGE, 2, 3}, {&LAX, "LAX", ZEROPAGE, 2, 3}, {&TAY, "TAY", IMPLICIT, 1, 2}, {&LDA, "LDA", IMMEDIATE, 2, 2},
    {&TAX, "TAX", IMPLICIT, 1, 2}, {&OAL, "OAL", IMMEDIATE, 2, 2}, {&LDY, "LDY", ABSOLUTE, 3, 4}, {&LDA, "LDA", ABSOLUTE, 3, 4}, {&LDX, "LDX", ABSOLUTE, 3, 4}, {&LAX, "LAX", ABSOLUTE, 3, 4}, {&BCS, "BCS", RELATIVE, 2, 2}, {&LDA, "LDA", INDIRECTY, 2, -5}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&LAX, "LAX", INDIRECTY, 2, -5},
    {&LDY, "LDY", ZEROPAGEX, 2, 4}, {&LDA, "LDA", ZEROPAGEX, 2, 4}, {&LDX, "LDX", ZEROPAGEY, 2, 4}, {&LAX, "LAX", ZEROPAGEY, 2, 4}, {&CLV, "CLV", IMPLICIT, 1, 2}, {&LDA, "LDA", ABSOLUTEY, 3, -4}, {&TSX, "TSX", IMPLICIT, 1, 2}, {&LAS, "LAS", ABSOLUTEY, 3, -4}, {&LDY, "LDY", ABSOLUTEX, 3, -4}, {&LDA, "LDA", ABSOLUTEX, 3, -4},
    {&LDX, "LDX", ABSOLUTEY, 3, -4}, {&LAX, "LAX", ABSOLUTEY, 3, -4}, {&CPY, "CPY", IMMEDIATE, 2, 2}, {&CMP, "CMP", INDIRECTX, 2, 6}, {&NOP, "NOP", IMMEDIATE, 2, 2}, {&DCM, "DCM", INDIRECTX, 2, 8}, {&CPY, "CPY", ZEROPAGE, 2, 3}, {&CMP, "CMP", ZEROPAGE, 2, 3}, {&DEC, "DEC", ZEROPAGE, 2, 5}, {&DCM, "DCM", ZEROPAGE, 2, 5},
    // 200
    {&INY, "INY", IMPLICIT, 1, 2}, {&CMP, "CMP", IMMEDIATE, 2, 2}, {&DEX, "DEX", IMPLICIT, 1, 2}, {&SAX, "SAX", IMMEDIATE, 2, 2}, {&CPY, "CPY", ABSOLUTE, 3, 4}, {&CMP, "CMP", ABSOLUTE, 3, 4}, {&DEC, "DEC", ABSOLUTE, 3, 6}, {&DCM, "DCM", ABSOLUTE, 3, 6}, {&BNE, "BNE", RELATIVE, 2, 2}, {&CMP, "CMP", INDIRECTY, 2, -5},
    {&KIL, "KIL", IMPLICIT, 1, 1}, {&DCM, "DCM", INDIRECTY, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&CMP, "CMP", ZEROPAGEX, 2, 4}, {&DEC, "DEC", ZEROPAGEX, 2, 6}, {&DCM, "DCM", ZEROPAGEX, 2, 6}, {&CLD, "CLD", IMPLICIT, 1, 2}, {&CMP, "CMP", ABSOLUTEY, 3, -4}, {&NOP, "NOP", IMPLICIT, 1, 1}, {&DCM, "DCM", ABSOLUTEY, 3, 7},
    {&NOP, "NOP", INDIRECT, 3, 1}, {&CMP, "CMP", ABSOLUTEX, 3, -4}, {&DEC, "DEC", ABSOLUTEX, 3, 7}, {&DCM, "DCM", ABSOLUTEX, 3, 7}, {&CPX, "CPX", IMMEDIATE, 2, 2}, {&SBC, "SBC", INDIRECTX, 2, 6}, {&NOP, "NOP", IMMEDIATE, 2, 2}, {&ISB, "ISB", INDIRECTX, 2, 8}, {&CPX, "CPX", ZEROPAGE, 2, 3}, {&SBC, "SBC", ZEROPAGE, 2, 3},
    {&INC, "INC", ZEROPAGE, 2, 5}, {&ISB, "ISB", ZEROPAGE, 2, 5}, {&INX, "INX", IMPLICIT, 1, 2}, {&SBC, "SBC", IMMEDIATE, 2, 2}, {&NOP, "NOP", IMPLICIT, 1, 2}, {&SBC, "SBC", IMMEDIATE, 2, 2}, {&CPX, "CPX", ABSOLUTE, 3, 4}, {&SBC, "SBC", ABSOLUTE, 3, 4}, {&INC, "INC", ABSOLUTE, 3, 6}, {&ISB, "ISB", ABSOLUTE, 3, 6},
    {&BEQ, "BEQ", RELATIVE, 2, 2}, {&SBC, "SBC", INDIRECTY, 2, -5}, {&KIL, "KIL", IMPLICIT, 1, 1}, {&ISB, "ISB", INDIRECTY, 2, 8}, {&NOP, "NOP", ABSOLUTEX, 2, 1}, {&SBC, "SBC", ZEROPAGEX, 2, 4}, {&INC, "INC", ZEROPAGEX, 2, 6}, {&ISB, "ISB", ZEROPAGEX, 2, 6}, {&SED, "SED", IMPLICIT, 1, 2}, {&SBC, "SBC", ABSOLUTEY, 3, -4},
    // 250
    {&NOP, "NOP", IMPLICIT, 1, 1}, {&ISB, "ISB", ABSOLUTEY, 3, 7}, {&NOP, "NOP", INDIRECT, 3, 1}, {&SBC, "SBC", ABSOLUTEX, 3, -4}, {&INC, "INC", ABSOLUTEX, 3, 7}, {&ISB, "ISB", ABSOLUTEX, 3, 7}
};
